name: Node.js CI

on:
  push:
    branches: ['dev']
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
      - run: echo ${{ secrets.TEST_ENV_VAR }}
      - run: echo ${{ vars.TEST_VARS }}
        
